'use strict';
const $=id=>document.getElementById(id), canvas=$('canvas'), ctx=canvas.getContext('2d');
const fields=['ratio','fit','panX','panY','name','title','viewers','likes','accent','dim','uiScale','showComments','showHearts','showLive','draftComment'];
let background=null, avatar=null, backgroundData=null, avatarData=null;
let comments=[{name:'sora',text:'こんばんは！今日も来ました 🌙'},{name:'haru',text:'この雰囲気、好き！'},{name:'yuki',text:'いつも配信ありがとう 🫶'},{name:'rina',text:'初見です！こんばんは ✨'}];
const colors=['#acbdf5','#f5b8cf','#b9dfc7','#e4c79b','#c7b9ec','#a5d8df','#edb4a4','#c4d29d'];
let toastTimer;
function notify(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3200)}
function state(){return Object.fromEntries(fields.map(id=>[id,$(id).type==='checkbox'?$(id).checked:$(id).value]))}
function rounded(x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill()}
function text(t,x,y,size=18,color='#fff',weight=400){ctx.font=`${weight} ${size}px "Segoe UI", "Yu Gothic UI", sans-serif`;ctx.fillStyle=color;ctx.fillText(t,x,y)}
function shorten(t,width,size,weight=400){ctx.font=`${weight} ${size}px "Segoe UI", "Yu Gothic UI", sans-serif`;let a=Array.from(t);if(ctx.measureText(t).width<=width)return t;while(a.length&&ctx.measureText(a.join('')+'…').width>width)a.pop();return a.join('')+'…'}
function heart(x,y,size,color){ctx.save();ctx.translate(x,y);ctx.scale(size/24,size/24);ctx.beginPath();ctx.moveTo(12,22);ctx.bezierCurveTo(9,18,0,13,0,6);ctx.bezierCurveTo(0,-1,9,-2,12,4);ctx.bezierCurveTo(15,-2,24,-1,24,6);ctx.bezierCurveTo(24,13,15,19,12,22);ctx.fillStyle=color;ctx.fill();ctx.restore()}
function circleAvatar(x,y,r,name,color,img){ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();ctx.fillStyle=color;ctx.fill();if(img){let s=Math.max(r*2/img.width,r*2/img.height);ctx.drawImage(img,x-img.width*s/2,y-img.height*s/2,img.width*s,img.height*s)}else{ctx.textAlign='center';text(Array.from(name.trim())[0]||'?',x,y+r*.36,r, '#fff',700);ctx.textAlign='left'}ctx.restore()}
function number(value){return Math.max(0,Math.min(999999999,Number(value)||0)).toLocaleString('ja-JP')}
function sample(w,h){const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#b48d82');g.addColorStop(.45,'#767280');g.addColorStop(1,'#283543');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.save();ctx.filter='blur(32px)';ctx.fillStyle='#ecc7a56b';ctx.beginPath();ctx.ellipse(w*.22,h*.25,w*.28,h*.32,-.35,0,Math.PI*2);ctx.fill();ctx.fillStyle='#243f3a88';ctx.beginPath();ctx.ellipse(w*.9,h*.65,w*.3,h*.36,.3,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.textAlign='center';text('Your moment,',w/2,h*.42,w*.072,'#ffffffb3',300);text('on air.',w/2,h*.42+w*.09,w*.072,'#ffffffb3',300);text('画像を追加して、配信画面をつくろう',w/2,h*.42+w*.15,Math.min(w*.024,25),'#ffffff8c');ctx.restore()}
function render(){const s=state(),wide=s.ratio==='landscape';canvas.width=wide?1920:1080;canvas.height=wide?1080:1920;const w=canvas.width,h=canvas.height;$('dimensions').textContent=`${w} × ${h}`;
 ctx.fillStyle='#181a20';ctx.fillRect(0,0,w,h);
 if(background){const scale=(s.fit==='cover'?Math.max:Math.min)(w/background.width,h/background.height);const dw=background.width*scale,dh=background.height*scale;ctx.drawImage(background,(w-dw)*Number(s.panX)/100,(h-dh)*Number(s.panY)/100,dw,dh)}else sample(w,h);
 ctx.fillStyle=`rgba(0,0,0,${Number(s.dim)/100})`;ctx.fillRect(0,0,w,h);
 const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#0007');grad.addColorStop(.23,'#0000');grad.addColorStop(.48,'#0000');grad.addColorStop(1,'#000b');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);
 const scale=2.4*Number(s.uiScale)/100;ctx.save();ctx.scale(scale,scale);const W=w/scale,H=h/scale,m=18;
 ctx.font='10px "Segoe UI", "Yu Gothic UI", sans-serif';const viewerLabel='◉ '+number(s.viewers),liveWidth=64+ctx.measureText(viewerLabel).width,liveX=W-40-liveWidth;
 const profileWidth=Math.min(s.showLive?liveX-m-8:W-58,wide?275:230);rounded(m,m,profileWidth,49,25,'#15151d77');circleAvatar(m+24,m+24,19,s.name,s.accent,avatar);text(shorten(s.name,profileWidth-60,14,700),m+51,m+22,14,'#fff',700);text('フォロー ＋',m+51,m+39,10,'#ffffffe0');
 if(s.showLive){rounded(liveX,m,liveWidth,28,14,'#15151d99');text('LIVE',liveX+10,m+19,12,s.accent,700);rounded(liveX+48,m+7,1,14,0,'#ffffff40');text(viewerLabel,liveX+56,m+18,10)}text('×',W-29,m+21,24,'#fff');
 text(shorten(s.title,W-2*m,13,600),m,m+76,13,'#fff',600);
 const actionX=W-37, bottom=H-43;
 if(s.showHearts){for(let i=0;i<6;i++){ctx.globalAlpha=.25+i*.1;heart(actionX-5+Math.sin(i*2)*13,bottom-155-i*22,12+(i%3)*5,s.accent)}ctx.globalAlpha=1}
 heart(actionX-13,bottom-63,27,s.accent);ctx.textAlign='center';text(number(s.likes),actionX,bottom-18,11,'#fff',700);
 ctx.textAlign='left';
 if(s.showComments){const maxWidth=wide?Math.min(480,W-95):W-95;const rowHeight=39,available=Math.max(0,H-225),visibleCount=Math.min(8,Math.floor(available/rowHeight));const visible=visibleCount?comments.slice(-visibleCount):[];visible.forEach((c,i)=>{const y=H-78-(visible.length-i)*rowHeight;circleAvatar(m+12,y+15,12,c.name,colors[(comments.length-visible.length+i)%colors.length]);text(shorten(c.name,maxWidth-39,11,700),m+34,y+11,11,'#ffffffe0',700);text(shorten(c.text.replace(/\n/g,' '),maxWidth-39,13),m+34,y+27,13)})}
 const inputWidth=W-66,inputRight=m+inputWidth,draft=s.draftComment.trim();rounded(m,H-54,inputWidth,34,17,'#ffffff20');text(shorten(draft||'コメントを追加…',inputWidth-57,12),m+13,H-32,12,draft?'#fff':'#ffffffba');ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';text('☺',inputRight-22,H-37,21,'#ffffffd0');ctx.restore();text('⋯',W-44,H-31,25);ctx.restore();
}
function renderComments(){const container=$('comments');container.replaceChildren();comments.forEach((c,i)=>{const row=document.createElement('div');row.className='comment';const name=document.createElement('input');name.value=c.name;name.maxLength=30;name.setAttribute('aria-label',`コメント${i+1}の名前`);name.placeholder='ユーザー名';const remove=document.createElement('button');remove.className='delete';remove.textContent='×';remove.setAttribute('aria-label',`コメント${i+1}を削除`);remove.onclick=()=>{comments.splice(i,1);renderComments();render()};const body=document.createElement('textarea');body.value=c.text;body.maxLength=200;body.setAttribute('aria-label',`コメント${i+1}の本文`);body.placeholder='コメントを入力';name.oninput=()=>{c.name=name.value;render()};body.oninput=()=>{c.text=body.value;render()};row.append(name,remove,body);container.append(row)});$('commentCount').textContent=`${comments.length} / 8`;$('addComment').disabled=comments.length>=8}
function decode(data){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('画像を読み込めませんでした。'));img.src=data})}
function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('ファイルを読み込めませんでした。'));reader.readAsDataURL(file)})}
let imageVersion=0,avatarVersion=0;
async function loadImage(file,isAvatar=false){if(!file)return;const version=isAvatar?++avatarVersion:++imageVersion;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('PNG・JPG・WebP画像を選択してください。');if(file.size>40*1024*1024)throw new Error('40MB以下の画像を選択してください。');const data=await readFile(file),img=await decode(data);if(version!==(isAvatar?avatarVersion:imageVersion))return;if(isAvatar){avatar=img;avatarData=data}else{background=img;backgroundData=data;$('imageInfo').textContent=`${file.name} · ${img.width} × ${img.height}`;$('ratio').value=img.width>img.height?'landscape':'portrait'}render()}catch(e){notify(e.message)}}
function download(blob,filename){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
fields.forEach(id=>$(id).addEventListener('input',render));$('image').onchange=e=>loadImage(e.target.files[0]);$('avatar').onchange=e=>loadImage(e.target.files[0],true);
$('removeImage').onclick=()=>{imageVersion++;background=null;backgroundData=null;$('image').value='';$('imageInfo').textContent='サンプル背景を表示中';render()};$('removeAvatar').onclick=()=>{avatarVersion++;avatar=null;avatarData=null;$('avatar').value='';render()};
$('drop').ondragover=e=>{e.preventDefault();$('drop').classList.add('drag')};$('drop').ondragleave=()=>$('drop').classList.remove('drag');$('drop').ondrop=e=>{e.preventDefault();$('drop').classList.remove('drag');loadImage(e.dataTransfer.files[0])};
$('addComment').onclick=()=>{if(comments.length<8){comments.push({name:'guest',text:'こんにちは！'});renderComments();render()}};
$('export').onclick=()=>{render();canvas.toBlob(blob=>{if(blob){download(blob,`live-screen-${canvas.width}x${canvas.height}.png`);notify('PNG画像を書き出しました')}else notify('書き出しに失敗しました。')},'image/png')};
$('saveSettings').onclick=()=>{download(new Blob([JSON.stringify({version:1,settings:state(),comments,background:backgroundData,avatar:avatarData},null,2)],{type:'application/json'}),'live-screen-settings.json');notify('画像を含む設定を保存しました')};
$('loadSettings').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>115*1024*1024)throw new Error('設定ファイルが大きすぎます。');const d=JSON.parse(await file.text());if(d.version!==1||!d.settings||!Array.isArray(d.comments)||d.comments.length>8)throw new Error('設定ファイルの形式が違います。');const cleanComments=d.comments.map(c=>{if(typeof c?.name!=='string'||typeof c?.text!=='string')throw new Error('コメントの形式が違います。');return {name:c.name.slice(0,30),text:c.text.slice(0,200)}});for(const key of ['background','avatar'])if(d[key]!=null&&(typeof d[key]!=='string'||!/^data:image\/(png|jpeg|webp);base64,/.test(d[key])))throw new Error('画像データの形式が違います。');const [bg,av]=await Promise.all([d.background?decode(d.background):null,d.avatar?decode(d.avatar):null]);imageVersion++;avatarVersion++;for(const id of fields){const el=$(id),v=d.settings[id];if(v===undefined)continue;if(el.type==='checkbox'){if(typeof v==='boolean')el.checked=v}else if(el.tagName==='SELECT'){if([...el.options].some(o=>o.value===v))el.value=v}else if(el.type==='range'||el.type==='number'){if(Number.isFinite(Number(v)))el.value=String(Math.max(Number(el.min),Math.min(Number(el.max),Number(v))))}else if(el.type==='color'){if(/^#[0-9a-f]{6}$/i.test(v))el.value=v}else if(typeof v==='string')el.value=v.slice(0,el.maxLength>0?el.maxLength:200)}comments=cleanComments;background=bg;avatar=av;backgroundData=d.background||null;avatarData=d.avatar||null;$('image').value='';$('avatar').value='';$('imageInfo').textContent=bg?`設定から復元 · ${bg.width} × ${bg.height}`:'サンプル背景を表示中';renderComments();render();notify('設定を読み込みました')}catch(err){notify('読み込み失敗：'+err.message)}finally{e.target.value=''}};
renderComments();render();
